## RNN(Recurrent Neural Network) : 순환 신경망
#### 순서가 있는 시퀀스 데이터, time series data(시계열 데이터)를 입력하여 예측

In [1]:
import tensorflow as tf
import numpy as np

!pip install IPython 
from IPython.display import Image

### One cell: 4 (input_dim) in 2 (hidden_size)

![image](https://cloud.githubusercontent.com/assets/901975/23348727/cc981856-fce7-11e6-83ea-4b187473466b.png)

In [2]:
# One hot encoding for each char in 'hello'
h = [1, 0, 0, 0]
e = [0, 1, 0, 0]
l = [0, 0, 1, 0]
o = [0, 0, 0, 1]

In [3]:
# One cell RNN input_dim (4) -> output_dim (2)
x_data = np.array([[h]],dtype=np.float32)
hidden_size = 2

rnn = tf.keras.layers.SimpleRNN(units=hidden_size,return_sequences=True,
                               return_state=True)
outputs,states = rnn(x_data)

print('x_data: {}, shape: {}'.format(x_data, x_data.shape)) # (N,T,D)
print('outputs: {}, shape: {}'.format(outputs, outputs.shape)) # (N,T,H)
print('states: {}, shape: {}'.format(states, states.shape)) # (N,H)
#  N :batch_size, T : sequence Length, D : input dimensize, H : hidden size

x_data: [[[1. 0. 0. 0.]]], shape: (1, 1, 4)
outputs: [[[0.43626824 0.43326256]]], shape: (1, 1, 2)
states: [[0.43626824 0.43326256]], shape: (1, 2)


### Unfolding to n sequences

![image](https://cloud.githubusercontent.com/assets/901975/23383634/649efd0a-fd82-11e6-925d-8041242743b0.png)

In [5]:
# One cell RNN input_dim (4) -> output_dim (2), sequence: 5
x_data = np.array([[h, e, l, l, o]], dtype=np.float32)

hidden_size = 2

rnn = tf.keras.layers.SimpleRNN(units=hidden_size,return_sequences=True,
                               return_state=True)
outputs,states = rnn(x_data)

print('x_data: {}, shape: {}'.format(x_data, x_data.shape)) 
print('outputs: {}, shape: {}'.format(outputs, outputs.shape)) 
print('states: {}, shape: {}'.format(states, states.shape)) 

x_data: [[[1. 0. 0. 0.]
  [0. 1. 0. 0.]
  [0. 0. 1. 0.]
  [0. 0. 1. 0.]
  [0. 0. 0. 1.]]], shape: (1, 5, 4)
outputs: [[[-0.3574105   0.09704847]
  [ 0.20303991  0.3972371 ]
  [-0.29320306  0.6307372 ]
  [-0.21304035  0.85763526]
  [-0.85977846  0.7477944 ]]], shape: (1, 5, 2)
states: [[-0.85977846  0.7477944 ]], shape: (1, 2)


### Batching input

![image](https://cloud.githubusercontent.com/assets/901975/23383681/9943a9fc-fd82-11e6-8121-bd187994e249.png)

In [6]:
# One cell RNN input_dim (4) -> output_dim (2). sequence: 5, batch 3
# 3 batches 'hello', 'eolll', 'lleel'
x_data = np.array([[h, e, l, l, o],
                   [e, o, l, l, l],
                   [l, l, e, e, l]], dtype=np.float32)

hidden_size = 2

rnn = tf.keras.layers.SimpleRNN(units=hidden_size,return_sequences=True,
                               return_state=True)
outputs,states = rnn(x_data)

print('x_data: {}, shape: {}'.format(x_data, x_data.shape)) 
print('outputs: {}, shape: {}'.format(outputs, outputs.shape)) 
print('states: {}, shape: {}'.format(states, states.shape)) 

x_data: [[[1. 0. 0. 0.]
  [0. 1. 0. 0.]
  [0. 0. 1. 0.]
  [0. 0. 1. 0.]
  [0. 0. 0. 1.]]

 [[0. 1. 0. 0.]
  [0. 0. 0. 1.]
  [0. 0. 1. 0.]
  [0. 0. 1. 0.]
  [0. 0. 1. 0.]]

 [[0. 0. 1. 0.]
  [0. 0. 1. 0.]
  [0. 1. 0. 0.]
  [0. 1. 0. 0.]
  [0. 0. 1. 0.]]], shape: (3, 5, 4)
outputs: [[[ 0.12823658 -0.51648706]
  [-0.22983275 -0.59393924]
  [ 0.45204484 -0.8192388 ]
  [-0.11090545 -0.91398036]
  [-0.45711732 -0.47855002]]

 [[-0.2412594  -0.15054624]
  [-0.5143717   0.24467565]
  [ 0.49394122 -0.26415873]
  [-0.28925702 -0.7725638 ]
  [ 0.53102607 -0.864581  ]]

 [[ 0.10890134 -0.5661937 ]
  [ 0.1519726  -0.8387096 ]
  [-0.17049682 -0.7619526 ]
  [ 0.11820138 -0.6868661 ]
  [ 0.1741271  -0.8706301 ]]], shape: (3, 5, 2)
states: [[-0.45711732 -0.47855002]
 [ 0.53102607 -0.864581  ]
 [ 0.1741271  -0.8706301 ]], shape: (3, 2)
