In [1]:
### multi-variable Linear Regression : 다항 회귀

import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt  
tf.random.set_seed(5)

In [2]:
# 학습 데이터 : X,Y
x_data = [[73.,80.,75.],
          [93.,88.,93.],
          [89.,91.,90.],
          [96.,98.,100.],
          [73.,66.,70.]]

y_data = [[152.],
          [185.],
          [180.],
          [196.],
          [142.]]
x_train = np.array(x_data,dtype=np.float32)
y_train = np.array(y_data,dtype=np.float32)
x_train.shape, y_train.shape

((5, 3), (5, 1))

In [3]:
# 변수 초기화 : weight, bias
#   X   *   W   = Y
# (m,n) * (n,l) = (m,l)   : 행렬의 내적 곱셈 공식

# 연습용 예제
# (10,3) * (_,_) = (10,1)         :    W->(3,1)
# (1024,768) * (_,_) = (1024,1)   :    W->(768,1)

# (5,3) * (3,1) = (5,1)
W = tf.Variable(tf.random.normal([3,1]),name='weight')
b = tf.Variable(tf.random.normal([1]),name='bias')
print(W)
print(b)

<tf.Variable 'weight:0' shape=(3, 1) dtype=float32, numpy=
array([[-0.18030666],
       [-0.95028627],
       [-0.03964049]], dtype=float32)>
<tf.Variable 'bias:0' shape=(1,) dtype=float32, numpy=array([0.22652863], dtype=float32)>


In [4]:
# 예측 함수(hypothesis) : H(X1,X2,X3) = W1*X1 + W2*X2 + W3*X3 + b
def hypothesis(X):
    return tf.matmul(X,W) + b  # 내적 곱셈

In [5]:
# 비용 함수 : (Hx - y)^2 의 평균
# tf.square()      : 제곱
# tf.reduce_mean() : 합의 평균
def cost_func():
    cost = tf.reduce_mean(tf.square(hypothesis(x_train) - y_train))
    return cost

In [6]:
# 경사 하강법
# optimizer = tf.compat.v1.train.GradientDescentOptimizer(learning_rate=0.01)
# optimizer = tf.compat.v1.train.AdamOptimizer(learning_rate=0.01)
optimizer = tf.keras.optimizers.Adam(learning_rate=0.01)

In [7]:
# 학습 시작
print('***** Start Learning!!')
for step in range(10001):
    optimizer.minimize(cost_func,var_list=[W,b])
    if step % 100 == 0:
        print('%04d'%step,'cost:[',cost_func().numpy(),']',
             ' W:',W.numpy(),' b:',b.numpy())
print('***** Learning Finished!!') 

***** Start Learning!!
0000 cost:[ 72495.52 ]  W: [[-0.17030665]
 [-0.9402863 ]
 [-0.02964049]]  b: [0.23652864]
0100 cost:[ 4484.4697 ]  W: [[ 0.6139679 ]
 [-0.15593217]
 [ 0.754649  ]]  b: [1.0209029]
0200 cost:[ 39.031322 ]  W: [[0.8497376 ]
 [0.08022431]
 [0.99049103]]  b: [1.2571564]
0300 cost:[ 1.8185711 ]  W: [[0.8725854 ]
 [0.10369529]
 [1.0134547 ]]  b: [1.2807845]
0400 cost:[ 1.7926762 ]  W: [[0.872841  ]
 [0.10471869]
 [1.0138539 ]]  b: [1.2820022]
0500 cost:[ 1.7869034 ]  W: [[0.8724857 ]
 [0.10525567]
 [1.0136645 ]]  b: [1.2827669]
0600 cost:[ 1.7803853 ]  W: [[0.87208366]
 [0.10586476]
 [1.0134504 ]]  b: [1.2836365]
0700 cost:[ 1.7731373 ]  W: [[0.87163574]
 [0.1065436 ]
 [1.0132116 ]]  b: [1.2846084]
0800 cost:[ 1.7651775 ]  W: [[0.8711428 ]
 [0.10729134]
 [1.0129483 ]]  b: [1.285682]
0900 cost:[ 1.7565353 ]  W: [[0.87060463]
 [0.10810767]
 [1.0126605 ]]  b: [1.2868584]
1000 cost:[ 1.7471693 ]  W: [[0.8700216 ]
 [0.10899291]
 [1.0123482 ]]  b: [1.2881387]
1100 cost:[ 1.7

In [8]:
# weight과 bias 출력
print('Weight:',W.numpy())
print('Bias:',b.numpy())

Weight: [[0.7881197 ]
 [0.40086928]
 [0.7815135 ]]
Bias: [3.3375585]


In [9]:
# 예측
print('***** Predict')
x_data = [[73.,80.,75.],
          [93.,88.,93.],
          [89.,91.,90.],
          [96.,98.,100.],
          [73.,66.,70.]]
x_test = np.array(x_data,dtype=np.float32)
print(hypothesis(x_test).numpy())
# [[151.85255]
#  [184.6879 ]
#  [180.52733]
#  [196.38217]
#  [142.34824]]
# y_data = [[152.],
#           [185.],
#           [180.],
#           [196.],
#           [142.]]

***** Predict
[[151.55334]
 [184.58994]
 [180.29553]
 [196.43358]
 [142.03362]]
