In [3]:
# XOR : 1 layer
# 이진 분류 : Logistic Regression
# 활성화 함수 : sigmoid 함수 사용
import tensorflow as tf
import numpy as np
tf.random.set_seed(5)

In [4]:
# train data set 
x_data = [[0,0],
          [0,1],
          [1,0],
          [1,1]]

y_data = [[0],
          [1],
          [1],
          [0]]

x_train = np.array(x_data,dtype=np.float32)
y_train = np.array(y_data,dtype=np.float32)

In [5]:
# 변수 초기화 : weight, bias
#   X   *   W   = Y
# (m,n) * (n,l) = (m,l)   : 행렬의 내적 곱셈 공식
# (4,2) * (2,1) = (4,1)
W = tf.Variable(tf.random.normal([2,1]),name='weight')
b = tf.Variable(tf.random.normal([1]),name='bias')
print(W)
print(b)

<tf.Variable 'weight:0' shape=(2, 1) dtype=float32, numpy=
array([[-0.18030666],
       [-0.95028627]], dtype=float32)>
<tf.Variable 'bias:0' shape=(1,) dtype=float32, numpy=array([0.22652863], dtype=float32)>


In [6]:
# 예측 함수(hypothesis) : H(X) = sigmoid(X*W + B)
def hypothesis(X):
    return tf.sigmoid(tf.matmul(X,W) + b)  # 0과 1사이의 값이 출력

In [7]:
# 비용 함수 : logloss, 2진분류모델
def cost_func():
    cost = -tf.reduce_mean(y_train*tf.math.log(hypothesis(x_train)) +
                          (1 - y_train)*tf.math.log(1-hypothesis(x_train)))
    return cost

In [8]:
# 경사 하강법
# learning_rate(학습율)을 0.01 로 설정하여 optimizer객체를 생성
optimizer = tf.keras.optimizers.Adam(learning_rate=0.01)

In [9]:
# 학습 시작
print('***** Start Learning!!')
for step in range(10001):
    optimizer.minimize(cost_func,var_list=[W,b])
    if step % 1000 == 0:
        print('%04d'%step,'cost:[',cost_func().numpy(),']',
             ' W:',W.numpy(),' b:',b.numpy())
print('***** Learning Finished!!') 

***** Start Learning!!
0000 cost:[ 0.7333479 ]  W: [[-0.1703073]
 [-0.9402866]]  b: [0.23652823]
1000 cost:[ 0.6931472 ]  W: [[1.6602307e-08]
 [2.4315691e-08]]  b: [-4.7717077e-08]
2000 cost:[ 0.6931472 ]  W: [[1.6602307e-08]
 [2.4315691e-08]]  b: [-4.7717077e-08]
3000 cost:[ 0.6931472 ]  W: [[1.6602307e-08]
 [2.4315691e-08]]  b: [-4.7717077e-08]
4000 cost:[ 0.6931472 ]  W: [[1.6602307e-08]
 [2.4315691e-08]]  b: [-4.7717077e-08]
5000 cost:[ 0.6931472 ]  W: [[1.6602307e-08]
 [2.4315691e-08]]  b: [-4.7717077e-08]
6000 cost:[ 0.6931472 ]  W: [[1.6602307e-08]
 [2.4315691e-08]]  b: [-4.7717077e-08]
7000 cost:[ 0.6931472 ]  W: [[1.6602307e-08]
 [2.4315691e-08]]  b: [-4.7717077e-08]
8000 cost:[ 0.6931472 ]  W: [[1.6602307e-08]
 [2.4315691e-08]]  b: [-4.7717077e-08]
9000 cost:[ 0.6931472 ]  W: [[1.6602307e-08]
 [2.4315691e-08]]  b: [-4.7717077e-08]
10000 cost:[ 0.6931472 ]  W: [[1.6602307e-08]
 [2.4315691e-08]]  b: [-4.7717077e-08]
***** Learning Finished!!


In [10]:
# weight과 bias 출력
print('Weight:',W.numpy())
print('Bias:',b.numpy())

Weight: [[1.6602307e-08]
 [2.4315691e-08]]
Bias: [-4.7717077e-08]


In [12]:
# 예측
# tf.argmax() : 값이 가장 큰 요소의 인덱스 값을 반환
def predict(X):
    return tf.argmax(hypothesis(X),axis=1)

# 학습 데이터를 검증 데이터로 동일하게 사용하는 경우
x_test = x_train
y_test = y_train

preds = predict(x_test)
print(preds.numpy())
print(hypothesis(x_test).numpy())

# 1층(단층) 신경망으로 XOR Problem 해결 불가

[0 0 0 0]
[[0.49999997]
 [0.5       ]
 [0.49999997]
 [0.5       ]]
